# Generated by Django 6.0.2 on 2026-02-10 17:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShwaryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shwary_id', models.CharField(db_index=True, help_text="L'identifiant unique retourné par l'API Shwary", max_length=100, unique=True, verbose_name='ID Shwary')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('currency', models.CharField(default='CDF', max_length=3, verbose_name='Devise')),
                ('phone_number', models.CharField(help_text='Format E.164 (ex. +243...)', max_length=20, verbose_name='Numéro de téléphone')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Réussi'), ('failed', 'Échoué')], db_index=True, default='pending', max_length=20)),
                ('is_sandbox', models.BooleanField(default=True, help_text='Vrai si la transaction a été faite en environnement de teste.', verbose_name='Mode Sandbox')),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Stocke la réponse complète de Shwary pour débogage.', verbose_name='Réponse API brute')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Transaction Shwary',
                'verbose_name_plural': 'Transactions Shwary',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['shwary_id', 'status'], name='dj_shwary_s_shwary__fb5afe_idx'), models.Index(fields=['content_type', 'object_id'], name='dj_shwary_s_content_279467_idx')],
            },
        ),
    ]
