# Generated by Django 6.0.2 on 2026-02-20 14:38

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_shwary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shwarytransaction',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Stocke la réponse complète de Shwary pour débogage.', verbose_name='Réponse API brute'),
        ),
        migrations.AlterField(
            model_name='shwarytransaction',
            name='shwary_id',
            field=models.CharField(blank=True, help_text="L'identifiant unique retourné par l'API Shwary", max_length=100, null=True, unique=True, verbose_name='ID Shwary'),
        ),
    ]
